[package]
name = "bedrock-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bedrock_core = { path = "bedrock_core" }

protocol = { path = "protocol" }

serialize = { path = "serialize" }
serialize_derive = { path = "serialize_derive" }