[package]
name = "bedrockrs_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bedrockrs_core = { path = "../core" }
bedrockrs_proto_core = { path = "../proto_core" }
bedrockrs_macros = { path = "../macros" }

log = "0.4"

byteorder = "1.5.0"
varint-rs = "2.2"
